server:
  port: 40002
spring:
  application:
    name: mortalmall-product-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mortalmall_product
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:30003/eureka
  instance:
    prefer-ip-address: true
mybatis-plus:
  mapper-locations: classpath:com/mortal/mortalmall/mapper/*Mapper.xml
  type-aliases-package: com.mortal.mortalmall.domain,com.mortal.mortalmall.query
